# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: chenJF # your blog title name
subtitle:  
author: chen_JF # 作者
language: zh-CN
timezone: 

# custom Site settings
# more detail check out docs
SEOTitle: chenJF's blog 
header-img: //o7bkkhiex.bkt.clouddn.com/lion-blur-bg.jpg
email: chencjfeng@163.com
description: "一个逗比的程序员从写博客开始"
keyword: # seo key words

favicon: # your favicon png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://chencjfeng.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# SNS settings
# RSS:
weibo_username: ChenJF-X贱
zhihu_username: 
github_username: chencjfeng
twitter_username: 
facebook_username:  
linkedin_username:  

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 
disqus_username: 

# Duoshuo settings
duoshuo_username:  # 你的多说帐号
# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  mobile_sites: weibo,qq,wechat  # 移动端显示的分享图标

# Use livere
use_livere:

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar-about-description: Stay Hungry Stay Foolish # 个人描述
sidebar-avatar: /images/header.jpg    # use absolute URL


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 999              # A tag will be featured if the size of it is more than this condition value

# friends
friends:  # 友链

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions


markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji

## Themes: https://hexo.io/themes/
theme: Anisina



# Deployment
## Docs: https://hexo.io/docs/deployment.html
#部署到git上
deploy:
  type: git
  repo: https://github.com/chencjfeng/chencjfeng.github.io.git
  branch: master



# 导航栏
menu:
  home: /
  archives: /archives
  tags: /tags


# img CDN path
cdn-url:  # 你的CDN地址

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "/images/header.jpg"
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
post-default-img: /images/blog-bg-black-run.jpg #博文默认的图片
post-default-img-mobile: /images/blog-bg-black-run.jpg #移动端显示的图片
post-default-img-mobile-header: /images/earth.jpg #移动端头部背景图片

# search api , set your custom key
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search


# archive page title
archive:
    title: 归档
    description: 可以根据归档日期检索所有文件

# tags page title
tags:
    title: 标签
    description: 可以根据标签检索所有文件






